// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuplidoresBlazor.DAL;

namespace SuplidoresBlazor.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20200705043256_Inicio")]
    partial class Inicio
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("SuplidoresBlazor.Models.Ordenes", b =>
                {
                    b.Property<int>("ordenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("monto")
                        .HasColumnType("TEXT");

                    b.Property<int>("suplidorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ordenId");

                    b.ToTable("Ordenes");
                });

            modelBuilder.Entity("SuplidoresBlazor.Models.OrdenesDetalle", b =>
                {
                    b.Property<int>("ordenDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Importe")
                        .HasColumnType("TEXT");

                    b.Property<int>("cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("costo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ordenId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("productoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ordenDetalleId");

                    b.HasIndex("ordenId");

                    b.ToTable("OrdenesDetalle");
                });

            modelBuilder.Entity("SuplidoresBlazor.Models.Productos", b =>
                {
                    b.Property<int>("productoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("costo")
                        .HasColumnType("TEXT");

                    b.Property<string>("descripcion")
                        .HasColumnType("TEXT");

                    b.Property<int>("inventario")
                        .HasColumnType("INTEGER");

                    b.HasKey("productoId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            productoId = 1,
                            costo = 100m,
                            descripcion = "Cacao",
                            inventario = 0
                        },
                        new
                        {
                            productoId = 2,
                            costo = 100m,
                            descripcion = "Chocolate",
                            inventario = 0
                        });
                });

            modelBuilder.Entity("SuplidoresBlazor.Models.Suplidores", b =>
                {
                    b.Property<int>("suplidorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("suplidorId");

                    b.ToTable("Suplidores");

                    b.HasData(
                        new
                        {
                            suplidorId = 1,
                            nombre = "Rizek"
                        },
                        new
                        {
                            suplidorId = 2,
                            nombre = "Supremo"
                        });
                });

            modelBuilder.Entity("SuplidoresBlazor.Models.OrdenesDetalle", b =>
                {
                    b.HasOne("SuplidoresBlazor.Models.Ordenes", null)
                        .WithMany("OrdenDetalles")
                        .HasForeignKey("ordenId");
                });
#pragma warning restore 612, 618
        }
    }
}
